train_dir: "datasets/ForenSyth/Training"
val_dir: "datasets/ForenSyth/Validation"
test_dir: "datasets/ForenSyth/Testing"

batch_size: 32
image_size: 224
num_workers: 4
epochs: 20
lr: 0.0001
beta: 0.001
